export enum RequestStatus {
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  FAILED = 'FAILED',
}

export enum SagaState {
  RESERVING_HCM = 'RESERVING_HCM',
  AWAITING_APPROVAL = 'AWAITING_APPROVAL',
  COMMITTING_HCM = 'COMMITTING_HCM',
  COMPENSATING_HCM = 'COMPENSATING_HCM',
  TERMINAL = 'TERMINAL',
}

export enum MovementType {
  PENDING_RESERVATION = 'PENDING_RESERVATION',
  CONFIRMED = 'CONFIRMED',
  CANCELLED = 'CANCELLED',
  HCM_REFRESH = 'HCM_REFRESH',
}

export enum Role {
  EMPLOYEE = 'employee',
  MANAGER = 'manager',
  ADMIN = 'admin',
}
